name: Docker Image CI

on:
  push:
    branches: [ main , master ]
  pull_request:
    branches: [ main , master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag iliasrais/project-service:latest
      
    - name: Push the Docker image
      run: docker push iliasrais/project-service:latest
